POST https://localhost:7138/list/getlist HTTP/1.1
Content-Type: application/json
Authorization:  Barrier eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoxMjN9.t-Gw-kcA3ga6rd_qOJTfxM9bAGS3tIJMh0jvolET0FI

{}