POST https://localhost:7138/test/getlist HTTP/1.1
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIxMjMiLCJyb2xlIjoiQ29uc3VtZXIiLCJleHBpcmF0aW9uIjoiMjAyMi0wMi0yM1QwNDoxNzoyNS42NjI3NDc3KzA2OjMwIn0.P5D--277N-eSf-geAVSvzeqVl7s0BJjVJCnElkM8u_4

{}

POST https://localhost:7138/test/login?uid=123 HTTP/1.1
Content-Type: application/json

















